AllCops:
  TargetRubyVersion:
    2.7.4

##############################################################################
#
# These *must* stay "false" because they will never work with ruumba:
# https://github.com/ericqweinstein/ruumba#fix-paths-and-unapplicable-cops
#
# Inapplicable Cops

Layout/ArgumentAlignment:
  Enabled: false
Layout/ArrayAlignment:
  Enabled: false
Layout/BlockAlignment:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/FirstArgumentIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/InitialIndentation:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Layout/LeadingEmptyLines:
  Exclude:
    - 'app/views/epub_search_logs/index.html.erb.rb'
Layout/LineLength:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false
Layout/SpaceAfterComma:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideStringInterpolation:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false

Lint/Void:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Exclude:
    - 'app/views/catalog/_facets.html.erb.rb'
    - 'app/views/monograph_catalog/_index_monograph.html.erb.rb'
    - 'app/views/shared/_altmetric_dimensions.html.erb.rb'
    - 'app/views/shared/_brand_press_bar_custom.html.erb.rb'

Naming/FileName:
  Exclude:
    - 'app/views/layouts/mozilla-pdf-viewer.html.erb.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

##############################################################################
#
# Deviations from Defaults

Lint/AssignmentInCondition:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false

Style/EmptyElse:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Next:
  Enabled: false
Style/RedundantInterpolation:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
