# Put any overides here
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/controllers/curation_concerns/monographs_controller_spec.rb'
    - 'spec/controllers/roles_controller_spec.rb'

Metrics/BlockLength:
  Enabled: true
  Max: 295 # default is 25

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/riiif/file.rb'
    - 'app/controllers/downloads_controller.rb'
    - 'app/controllers/curation_concerns/file_sets_controller.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/riiif/file.rb'
    - 'app/controllers/downloads_controller.rb'
    - 'app/controllers/curation_concerns/file_sets_controller.rb'

Rails/Exit:
  Exclude:
    - 'lib/**/*'

Rails/OutputSafety:
  Exclude:
    - 'spec/presenters/concerns/title_presenter_spec.rb'
    - 'config/initializers/explain_partials.rb'
    - 'app/services/markdown_service.rb'
    - 'app/helpers/markdown_helper.rb'
    - 'app/helpers/gallery_helper.rb'
    - 'app/renderers/curation_concerns/renderers/attribute_renderer.rb'
    - 'app/renderers/curation_concerns/renderers/markdown_attribute_renderer.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/jobs/characterize_job_spec.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/actors/curation_concerns/monograph_actor_spec.rb'

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/EmptyLineAfterSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: true
  Max: 103 # default is 5

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/SubjectStub:
  Exclude:
    - 'spec/models/riiif/file_spec.rb'

RSpec/VerifiedDoubles:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'lib/import/importer.rb'
    - 'lib/import/csv_parser.rb'
    - 'spec/views/curation_concerns/file_sets/show.html.erb_spec.rb'
    - 'spec/views/curation_concerns/file_sets/_media.html.erb_spec.rb'
    - 'app/renderers/curation_concerns/renderers/*'
    - 'app/models/riiif/file.rb'

Style/GuardClause:
  Exclude:
    - 'lib/import/importer.rb'

Style/RedundantReturn:
  Exclude:
    - 'app/presenters/concerns/analytics_presenter.rb'
