# Put any overides here
Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/riiif/file.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/riiif/file.rb'
    - 'app/controllers/downloads_controller.rb'

Style/RedundantReturn:
  Exclude:
    - 'app/presenters/concerns/analytics_presenter.rb'
