language: ruby
cache: bundler
sudo: required
bundler_args: --without production
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - bin/bundle exec bin/setup
rvm:
  - 2.3.1
jdk:
  - oraclejdk8

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
