dist: trusty
language: ruby
cache: bundler
sudo: required
bundler_args: --without production
before_install:
  - gem update --system
  - gem install bundler:1.17.3
before_script:
  - bin/bundle exec bin/travis
rvm:
  - 2.4.2
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - dpkg # fix for travis issue https://github.com/travis-ci/travis-ci/issues/9361
  chrome: stable
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
