language: ruby
cache: bundler
sudo: required

before_install:
  - sudo apt-get install -qq clamav-daemon libclamav-dev clamav-data
  - sudo freshclam -v
before_script:
  - bundle exec bin/setup
rvm:
  - 2.3.0
jdk:
  - oraclejdk8

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
