# Do *not* use the active key in here, i.e. setting `active: false` until this issue is resolved and thoroughly tested:
# https://github:com/samvera/hyrax/issues/5316, see also https://tools.lib.umich.edu/jira/browse/HELIO-4084
# Once that is resolved, we can set the 3.0, 2.1 and 2.0 licenses back to `active: false` if desired

terms:
    - id: https://creativecommons.org/licenses/by/4.0/
      term: Creative Commons Attribution 4.0 International license
    - id: https://creativecommons.org/licenses/by-sa/4.0/
      term: Creative Commons Attribution-ShareAlike 4.0 International license
    - id: https://creativecommons.org/licenses/by-nd/4.0/
      term: Creative Commons Attribution-NoDerivatives 4.0 International license
    - id: https://creativecommons.org/licenses/by-nc/4.0/
      term: Creative Commons Attribution-NonCommercial 4.0 International license
    - id: https://creativecommons.org/licenses/by-nc-nd/4.0/
      term: Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International license
    - id: https://creativecommons.org/licenses/by-nc-sa/4.0/
      term: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license
    - id: https://creativecommons.org/publicdomain/zero/1.0/
      term: Creative Commons Zero license (implies pd)
    - id: https://creativecommons.org/publicdomain/mark/1.0/
      term: Creative Commons Public Domain Mark 1.0
    - id: https://www.press.umich.edu/about/licenses#all-rights-reserved
      term: All Rights Reserved
    - id: https://creativecommons.org/licenses/by/3.0/
      term: Creative Commons Attribution license, 3.0 Unported
    - id: https://creativecommons.org/licenses/by-nd/3.0/
      term: Creative Commons Attribution-NoDerivatives license, 3.0 Unported
    - id: https://creativecommons.org/licenses/by-nc-nd/3.0/
      term: Creative Commons Attribution-NonCommercial-NoDerivatives license, 3.0 Unported
    - id: https://creativecommons.org/licenses/by-nc/3.0/
      term: Creative Commons Attribution-NonCommercial license, 3.0 Unported
    - id: https://creativecommons.org/licenses/by-nc-sa/3.0/
      term: Creative Commons Attribution-NonCommercial-ShareAlike license, 3.0 Unported
    - id: https://creativecommons.org/licenses/by-sa/3.0/
      term: Creative Commons Attribution-ShareAlike license, 3.0 Unported
    - id: https://creativecommons.org/licenses/by-sa/2.1/jp/
      term: Creative Commons Attribution-ShareAlike 2.1 Japan
    - id: https://creativecommons.org/licenses/by/2.0/
      term: Creative Commons Attribution 2.0 Generic license
