terms:
- id: http://rightsstatements.org/vocab/InC/1.0/
  term: "In Copyright"
- id: http://rightsstatements.org/vocab/InC-OW-EU/1.0/
  term: "In Copyright - EU Orphan Work"
- id: http://rightsstatements.org/vocab/InC-EDU/1.0/
  term: "In Copyright - Educational Use Permitted"
- id: http://rightsstatements.org/vocab/InC-NC/1.0/
  term: "In Copyright - Non-Commercial Use Permitted"
- id: http://rightsstatements.org/vocab/InC-RUU/1.0/
  term: "In Copyright - Rights-holder(s) Unlocatable or Unidentifiable"
- id: http://rightsstatements.org/vocab/NoC-CR/1.0/
  term: "No Copyright - Contractual Restrictions"
- id: http://rightsstatements.org/vocab/NoC-NC/1.0/
  term: "No Copyright - Non-Commercial Use Only "
- id: http://rightsstatements.org/vocab/NoC-OKLR/1.0/
  term: "No Copyright - Other Known Legal Restrictions"
- id: http://rightsstatements.org/vocab/NoC-US/1.0/
  term: "No Copyright - United States"
- id: http://rightsstatements.org/vocab/CNE/1.0/
  term: "Copyright Not Evaluated"
- id: http://rightsstatements.org/vocab/UND/1.0/
  term: "Copyright Undetermined"
- id: http://rightsstatements.org/vocab/NKC/1.0/
  term: "No Known Copyright"
