terms:
    - id: 'British bells'
      term: 'British bells'
    - id: 'Dutch or French bells'
      term: 'Dutch or French bells'
    - id: 'Meantone temperament'
      term: 'Meantone temperament'
    - id: 'Historical carillon (18th-century or earlier)'
      term: 'Historical carillon (18th-century or earlier)'
