terms:
    - id: '2'
      term: '2'
    - id: '2.5'
      term: '2.5'
    - id: '3'
      term: '3'
    - id: '3.5'
      term: '3.5'
    - id: '4'
      term: '4'
    - id: '4.5'
      term: '4.5'
    - id: '5'
      term: '5'
    - id: '5.5'
      term: '5.5'
    - id: '6'
      term: '6'
