terms:
    - id: 'F2'
      term: 'F2'
    - id: 'G2'
      term: 'G2'
    - id: 'G#2'
      term: 'G#2'
    - id: 'A2'
      term: 'A2'
    - id: 'Bb2'
      term: 'Bb2'
    - id: 'B2'
      term: 'B2'
