terms:
    - id: 'Author created/owned'
      term: 'Author created/owned'
    - id: 'Public domain'
      term: 'Public domain'
    - id: 'in-copyright'
      term: in-copyright'
    - id: 'Fair use'
      term: 'Fair use'
