# Where things are
source: ./fulcrum
destination: ./public

# Site information
title: fulcrum
email: fulcrum-info@umich.edu
description: > # this means to ignore newlines until "url:"
  Fulcrum is a publishing platform that helps publishers present the
  full richness of their authors' research outputs in a durable, discoverable,
  accessible, and flexible form.
url: "https://fulcrum.org" # the base hostname & protocol for your site
twitter_username: fulcrumpub
github_username:  mlibrary/heliotrope

# Handling reading
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Jekyll will delete everything under public for security reasons. We want to keep these symlinks into `shared/public/`
keep_files: ["assets", "sitemaps", "system", "upload"]

# Conversion
markdown: kramdown

# Serving
baseurl: "" # the subpath of your site, e.g. /blog

# Outputting
permalink: /blog/:year/:month/:day/:title/
