# settings for curation concerns for the test environment, locally and on Travis:
# derivatives_path contains thumbnails and web-friendly audio, and video files for playbock
derivatives_path: <%= File.join(Rails.root, 'tmp', 'rspec_derivatives') %>
# uploads_path stashes files uploaded via the browser before ingest to fedora
# on distributed architectures, uploads_path must be on a drive shared with the web server
uploads_path: <%= File.join(Rails.root, 'tmp', 'uploads') %>
# minter_path tracks the ID of the last-created object
minter_path: <%= File.join(Rails.root, 'tmp', 'minter-state') %>

# aptrust_bags_path is the directory in which bags for aptrust will be created
aptrust_bags_path: <%= File.join(Rails.root, 'tmp', 'aptrust-bags') %>

resque_namespace: heliotrope-testing
host: test.host

keycard:
  database:
    adapter: sqlite
    database: db/keycard-test.sqlite3
    pool: 5
    timeout: 5000

checkpoint:
  database:
    adapter: sqlite
    database: db/checkpoint-test.sqlite3
    pool: 5
    timeout: 5000

handle_service:
  instantiate: false
  url: https://hdl.handle.net/api/handles
  user: admin
  password: secret
  ssl_verify: false

# List of Greensub Products to allow read access to everyone.
allow_read_products:
  - allow_read_product

# hopefully temporary, see HELIO-3678
bar_disallow_chapter_downloads_list:
  - sample_bar_number_1
  - sample_bar_number_2
